### ISSUE TITLE
Brief Flash of Light in Exhaust Trail

### ISSUE THREAD

**Issue by laifrank2002** [Clocks-in-a-Cooler/procyon_skies#6]
I think it's due to some opacity bug.

**Comment by Clocks-in-a-Cooler** [comment]
It is due to some opacity bug. It's more apparent if the server lags a lot.
The `alpha` of `Bubble` should be set to zero, but for some reason the camera ignores it...
Oh wait, I'm an idiot. I know how to fix it and I _can_ fix it. When I fix it, I'll post an explanation as to why this bug occurs and close this issue.

**Comment by Clocks-in-a-Cooler** [comment]
Three pieces of prerequisite information:
1. A `Bubble` fades, meaning that at the end of its life, its `alpha` is __zero__.
2. `camera.js` has a function to take `r`, `g`, and `b` values to convert into a colour. If an `alpha` value is present, it will take that too.
3. `0` evaulates to `false` in Javascript.

When a `Bubble` fades away, its `alpha` is `0`. The colour-converting function then tries to convert the `Bubble`'s colour. However, with an `alpha` of zero, the colour-converting function treats it as if `alpha` is not there (since `if(0)` evaluates to `false`). With colours, if there is no `alpha`, it is assumed to be `1`. _That_'s the brief flash of light.
